### ISSUE TITLE
Flasher.js Getting Started

### ISSUE THREAD

**Issue by chalkers** [thingsSDK/guides.thingssdk.com#1]
Write guide here: https://github.com/thingsSDK/guides.thingssdk.com/blob/master/flasher.js/getting_started.md

Here's some references to help: the project [readme](https://github.com/thingsSDK/flasher.js/blob/master/README.md) and [intro blog post](http://forefront.io/a/introducing-flasher-js/).

**Comment by samjulien** [comment]
I'm starting work on this one. I've been meaning to write an article about Flasher and the CLI, so it will be double duty anyway. I'm sure I'll need contributions from Mac and Linux users with some of the specifics, like the ports, but I'll get the bones up and a Windows tutorial. I'll be out of town this weekend but will shoot to have a first go of it up by the end of the following weekend.
