### ISSUE TITLE
Example Code: Using a Button

### ISSUE THREAD

**Issue by chalkers** [thingsSDK/guides.thingssdk.com#7]
Add example: https://github.com/thingsSDK/guides.thingssdk.com/blob/master/examples/using_a_button.md

Here's some sample code: https://github.com/thingsSDK/espruino-examples
Espruino Documentation: http://www.espruino.com/Reference

**Comment by ariesshrimp** [comment]
I'll write some of these up today. Gotta pop over and get some soldering supplies first
